# Generated by Django 5.1.2 on 2024-11-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_arquivo', models.CharField(max_length=1000)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('data_captura_exif', models.DateTimeField(blank=True, null=True)),
                ('data_digitizacao_exif', models.DateTimeField(blank=True, null=True)),
                ('data_modificacao_exif', models.DateTimeField(blank=True, null=True)),
                ('timestamp_json', models.IntegerField(blank=True, null=True)),
                ('formatted_json', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
