# Generated by Django 5.1.2 on 2024-11-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiza_media', '0003_rename_data_modificacao_exif_imagem_data_modificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='data_modificacao_exif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
